openapi: "3.0.0"
info:
  title: Insecure API Demo
  version: "1.0.0"
  description: |
    Example OpenAPI spec to demonstrate API Security scanning in Checkmarx.
    Endpoints intentionally contain insecure patterns (hardcoded keys, weak auth,
    SQL injection, and insecure deserialization).

servers:
  - url: http://localhost:5000

paths:
  /secure-data:
    get:
      summary: Retrieve secure data (insecure implementation)
      description: |
        This endpoint uses a weak query parameter token for authentication.
      parameters:
        - in: query
          name: token
          required: false
          schema:
            type: string
          description: Insecure query parameter used as auth token
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized

  /load:
    post:
      summary: Load serialized data (insecure deserialization)
      description: |
        This endpoint deserializes arbitrary input using pickle, which is unsafe.
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Loaded object

  /user-data:
    get:
      summary: Get user data (SQL injection vulnerable)
      description: |
        This endpoint is vulnerable because it directly interpolates the "id"
        query parameter into a SQL query without sanitization.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: User ID (unsanitized; potential SQL injection vector)
      responses:
        "200":
          description: User data
        "400":
          description: Bad request
