identifier: myRunningEnv
title: My Running Env
blueprint: githubRepoEnvironment
properties:
  url: https://example.com
  customBranchesPolicies: true
  protectedBranches: false
relations:
  repository: test-repo-0-174769878_herein
